# Name: Jaskirat Singh; Roll No:102017175; Subgroup: CS8

## Assignment 3

## Based on Data Scraping

Q1: For each of the best seller book mentioned on the first two pages of the following link:
https://www.amazon.in/gp/bestsellers/books/

Scrape the following information:
- Publisher
- Language
- Paperback
- ISBN-10
- ISBN-13
- Weight
- Dimensions
- First Three Customer Reviews

### Using Selenium

In [1]:
from selenium import webdriver
import requests
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
driver = webdriver.Chrome(ChromeDriverManager().install())

In [3]:
def get_books_links(pageno):
    url = "https://www.amazon.in/gp/bestsellers/books/ref=zg_bs_pg_"+str(pageno)+"?ie=UTF8&pg="+str(pageno)
    # print(url)
    driver.get(url)
    
    grids = driver.find_elements(By.CLASS_NAME, 'zg-grid-general-faceout')
    lst = []
    for el in grids:
        link = el.find_element(By.TAG_NAME, 'a')
        lst.append(link.get_attribute('href'))
    return lst

In [4]:
def get_books_details(urls):
    complete = []
    for url in urls:
        # print(url)
        driver.get(url)
        sub = []
        book_name = driver.find_element(By.ID, 'productTitle')
        sub.append(book_name.text)
        
        #getting unordered list
        unlst = driver.find_element(By.ID, 'detailBulletsWrapper_feature_div')
        lstitems = unlst.find_elements(By.TAG_NAME, 'li')
        count = 0
        # for item in lstitems:
        #     if(count<7):
        #         # print(item.text)
        #         res = item.text.partition(': ')[2]
        #         sub.append(res)
        #     count = count + 1
        # complete.append(sub)
        
        f = 0
        for item in lstitems:
            if "Publisher" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
            
        f = 0
        for item in lstitems:
            if "Language" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
        
        f = 0
        for item in lstitems:
            if "Paperback" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
            
        f = 0
        for item in lstitems:
            if "ISBN-10" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
            
        f = 0
        for item in lstitems:
            if "ISBN-13" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
            
        f = 0
        for item in lstitems:
            if "Weight" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
            
        f = 0
        for item in lstitems:
            if "Dimensions" in item.text:
                # print(item.text)
                res = item.text.partition(': ')[2]
                sub.append(res)
                f=1
                break
        if f==0:
            sub.append('NaN')
        
        
        hdr = driver.find_element(By.ID, 'cm-cr-dp-review-header')
        if "No customer reviews" not in hdr.text:
            reviews = driver.find_element(By.ID, 'cm-cr-dp-review-list')
            sub.append(reviews.text.replace("\n"," "))
        else:
            sub.append('NaN')
  
        complete.append(sub)
    return complete

In [5]:
l1 = get_books_links(1)
l2 = get_books_links(2)
l3 = l1+l2
ans = get_books_details(l3)
# ans

In [6]:
df = pd.DataFrame(ans, columns = ['Book Name', 'Publisher', 'Language', 'Paperback', 'ISBN-10', 'ISBN-13', 'Weight', 'Dimensions', 'Customer Reviews'])
df.head(10)

,Book Name,Publisher,Language,Paperback,ISBN-10,ISBN-13,Weight,Dimensions,Customer Reviews
0,It Starts With Us,Simon & Schuster; First Edition (18 October 20...,English,352 pages,1398518174,978-1398518179,493 g,15.2 x 2.3 x 22.8 cm,shresta kamath Good paper quality Reviewed in ...
1,Atomic Habits: The life-changing million copy ...,Random House Business Books (30 October 2018),English,288 pages,1847941834,978-1847941831,419 g,15.3 x 2.3 x 23.4 cm,Abhishek Rakhecha 4 Lesions I learnt from this...
2,It Ends With Us: A Novel: Volume 1,Simon & Schuser India; First Edition (5 August...,English,384 pages,1501110365,978-1501110368,295 g,13.49 x 2.29 x 20.96 cm,Arzoo Atlas Corrigan >>>>> Reviewed in India ðŸ‡®...
3,The Power of Your Subconscious Mind,Fingerprint! Publishing; 2017th edition (1 Feb...,English,256 pages,8172345666,978-8172345662,280 g,20.3 x 25.4 x 4.7 cm,Hari Must Read to boost your confidence. Revie...
4,The Psychology of Money,Jaico Publishing House (1 September 2020); Jai...,English,252 pages,9390166268,978-9390166268,220 g,20.3 x 25.4 x 4.7 cm,Anand Gupta It's not a book about investing Re...
5,Ikigai: The Japanese secret to a long and happ...,Random House UK (27 September 2017),English,NaN,178633089X,978-1786330895,247 g,13.6 x 2.3 x 18.4 cm,Mohammad Rafiq Found my PURPOSE to LIVE Review...
6,My First Library: Boxset of 10 Board Books for...,Wonder House Books; First edition (1 January 2...,English,NaN,9789387779266,978-9387779266,830 g,22 x 15 x 2.5 cm,Robin Worth buying Reviewed in India ðŸ‡®ðŸ‡³ on 27 ...
7,Brain Activity Book for Kids - 200+ Activities...,Maple Press Pvt Ltd; Kids Edition (1 September...,English,48 pages,9391924298,978-9391924294,160 g,22 x 28 x 0.3 cm,Channabasavana Gowda Good Reviewed in India ðŸ‡®ðŸ‡³...
8,Life's Amazing Secrets: How to Find Balance an...,Penguin Ananda (8 October 2018),English,232 pages,0143442295,978-0143442295,172 g,19.9 x 1.2 x 13.5 cm,Pavan A Manual for Life Reviewed in India ðŸ‡®ðŸ‡³ o...
9,"Build, Don't Talk: Things You Wish You Were Ta...",Penguin eBury Press (25 November 2022),English,224 pages,0143459686,978-0143459682,170 g,20.3 x 25.4 x 4.7 cm,Gaurav Gupta Must read in your 20's Reviewed i...

Q2: Consider the following Link:
https://www.imdb.com/search/title/?release_date=2020&sort=num_votes,desc&page=1

The page contains information about movies released in the year 2020 sorted according to number
of votes. Scrape the following information for the first 1000 movies.
- Movie name
- IMDB Rating
- Description 
- Votes
- Director(s)
- Stars 
- Metascore
- Movie Genre
- Total Duration

### Using selenium

In [7]:
from selenium import webdriver
import requests
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd

In [8]:
driver = webdriver.Chrome(ChromeDriverManager().install())

In [9]:
def imdb_data(pageno):
    #url = "https://www.imdb.com/search/title/?release_date=2020&sort=num_votes,desc&page=1"
    url = "https://www.imdb.com/search/title/?release_date=2020-01-01,2020-12-31&sort=num_votes,desc&start="+str(50*(pageno-1)+1)+"&ref_=adv_nxt"
    driver.get(url)
    complete = [] 
 
    titles = driver.find_elements(By.CLASS_NAME, "lister-item-header") 
    sub=[]
    for title in titles:
        sub.append(title.text[3:len(title.text)-7])
    complete.append(sub)

    imdb = driver.find_elements(By.TAG_NAME, 'strong')
    sub2=[]
    for rating in imdb:
        # print(rating.text)
        sub2.append(rating.text)
    complete.append(sub2[2:])  
    
    desc = [driver.find_elements(By.CLASS_NAME, 'text-muted')]
    # print(desc)
    sub3=[]
    for d in desc[0]:
        if len(d.text) > 55:
            sub3.append(d.text)
            # print(d.text)
            # print("\n")
    complete.append(sub3)
    
    
    votes = [driver.find_elements(By.CLASS_NAME, 'sort-num_votes-visible')]
    # print(votes)
    sub4=[]
    for v in votes[0]:
        #print(v.text[7:14])
        sub4.append(v.text[7:14])
    complete.append(sub4)
    
    meta_scores = driver.find_elements(By.CLASS_NAME, 'ratings-bar')
    # print(meta_scores)
    sub6=[]
    for meta_score in meta_scores:
        if(meta_score.text[14:16] != ""):
            sub6.append(meta_score.text[14:16])
        else:
            sub6.append('NaN')
        # print(meta_score.text[13:16])
    complete.append(sub6)
        
    genre = driver.find_elements(By.CLASS_NAME, 'genre')
    sub5=[]
    for g in genre:
        sub5.append(g.text)
    complete.append(sub5) 
    
    durations = driver.find_elements(By.CLASS_NAME, 'runtime')
    sub7=[]
    for duration in durations:
        sub7.append(duration.text)
        # print(duration.text)
    complete.append(sub7)
    
    return complete

In [10]:
# imdb_data(1)
df = pd.DataFrame(imdb_data(1)).transpose()

In [11]:
df.columns = ['Movie Name', 'IMDB Rating', 'Description','Votes', 'Metascore', 'Genre', 'Duration']
df.head()

,Movie Name,IMDB Rating,Description,Votes,Metascore,Genre,Duration
0,Tenet,7.3,"Armed with only one word, Tenet, and fighting ...","500,805",69,"Action, Sci-Fi, Thriller",150 min
1,The Queen's Gambit,8.6,"Orphaned at the tender age of nine, prodigious...","445,361",NaN,Drama,60 min
2,Soul,8.0,"After landing the gig of a lifetime, a New Yor...","328,330",83,"Animation, Adventure, Comedy",100 min
3,Wonder Woman 1984,5.4,"Diana must contend with a work colleague, and ...","267,158",60,"Action, Adventure, Fantasy",151 min
4,Birds of Prey,6.0,"After splitting with the Joker, Harley Quinn j...","239,262",60,"Action, Adventure, Comedy",109 min

### Using beautifulSoup

In [12]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np

In [13]:
def imdb_data(pageno):
    #url = "https://www.imdb.com/search/title/?release_date=2020&sort=num_votes,desc&page=1"
    url = "https://www.imdb.com/search/title/?release_date=2020-01-01,2020-12-31&sort=num_votes,desc&start="+str(50*(pageno-1)+1)+"&ref_=adv_nxt"
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser') 
    complete = [] 
    for d in soup.find_all('div', attrs={'class' : "lister-item mode-advanced"}):
        head = d.find('h3', attrs={'class':"lister-item-header"})#.replace('\n','')
        movie_name = head.find('a')

        imdb_div = d.find('div', attrs={'class':"inline-block ratings-imdb-rating"})
        imdb_rating = imdb_div.find('strong')
        
        desc_div = d.find('div', attrs={'class':"lister-item-content"})
        desc = desc_div.find_all('p', attrs={'class':"text-muted"})[1:2]
        
        votes_p = d.find('p', attrs={'class':"sort-num_votes-visible"})
        votes = votes_p.find('span', attrs={'name':'nv'})
        
        direc_ = d.find('p', attrs={'class':""})
        direc=[]
        
        check = direc_.find('span')
        
        for name in direc_.find_all(['a', 'span']):
            direc.append(name)
            
        direc_final=[]
        stars_final=[]
        
        if check is not None:
            for el in direc:
                direc_final.append(el)
                if el == check :
                    break
            
            for el in direc:
                if(el not in direc_final):
                    stars_final.append(el)
            
            direc_final.pop()
            
        else:
            stars_final = direc
            
        meta_score = d.find('div', attrs={'class':"inline-block ratings-metascore"})
        genre = d.find('span', attrs={'class':"genre"})
        duration = d.find('span', attrs={'class':"runtime"})
            
        sub = []
                        
        if movie_name is not None: # dealing with missing data
            sub.append(movie_name.text)
        else:
            sub.append('NaN')
        if imdb_rating is not None: 
            sub.append(imdb_rating.text)
        else:
            sub.append('NaN')
        if desc is not None: 
            sub.append(desc[0].text.strip())
        else:
            sub.append('NaN')
        if votes is not None: 
            sub.append(votes.text)
        else:
            sub.append('NaN')
        
        if direc_final != []: 
            sub.append((np.array(direc_final)).flatten()) 
        else:
            sub.append('NaN')
        
        if stars_final != []:
            sub.append((np.array(stars_final)).flatten())
        else:
            sub.append('NaN')

        if meta_score is not None: 
            sub.append(meta_score.text.replace("\n","")[:3]) 
        else:
            sub.append('NaN')
        if genre is not None: 
            sub.append(genre.text.strip())
        else:
            sub.append('NaN')
        if duration is not None: 
            sub.append(duration.text)
        else:
            sub.append('NaN')
        
        complete.append(sub)
        
    return complete

In [14]:
# imdb_data(1)
movies_df = pd.DataFrame(imdb_data(1), columns = ['Movie Name', 'IMDB Rating', 'Description','Votes', 'Directors','Stars', 'Metascore', 'Genre', 'Duration'])
movies_df.head(10)

,Movie Name,IMDB Rating,Description,Votes,Directors,Stars,Metascore,Genre,Duration
0,Tenet,7.3,"Armed with only one word, Tenet, and fighting ...","500,805",[Christopher Nolan],"[John David Washington, Robert Pattinson, Eliz...",69,"Action, Sci-Fi, Thriller",150 min
1,The Queen's Gambit,8.6,"Orphaned at the tender age of nine, prodigious...","445,361",NaN,"[Anya Taylor-Joy, Chloe Pirrie, Bill Camp, Mar...",NaN,Drama,60 min
2,Soul,8.0,"After landing the gig of a lifetime, a New Yor...","328,330","[Pete Docter, Kemp Powers]","[Jamie Foxx, Tina Fey, Graham Norton, Rachel H...",83,"Animation, Adventure, Comedy",100 min
3,Wonder Woman 1984,5.4,"Diana must contend with a work colleague, and ...","267,158",[Patty Jenkins],"[Gal Gadot, Chris Pine, Kristen Wiig, Pedro Pa...",60,"Action, Adventure, Fantasy",151 min
4,Birds of Prey and the Fantabulous Emancipation...,6.0,"After splitting with the Joker, Harley Quinn j...","239,262",[Cathy Yan],"[Margot Robbie, Rosie Perez, Mary Elizabeth Wi...",60,"Action, Adventure, Comedy",109 min
5,The Invisible Man,7.1,When Cecilia's abusive ex takes his own life a...,"228,816",[Leigh Whannell],"[Elisabeth Moss, Oliver Jackson-Cohen, Harriet...",72,"Drama, Horror, Mystery",124 min
6,A Quiet Place Part II,7.2,"Following the events at home, the Abbott famil...","227,288",[John Krasinski],"[Emily Blunt, Millicent Simmonds, Cillian Murphy]",71,"Drama, Horror, Sci-Fi",97 min
7,Ted Lasso,8.8,American college football coach Ted Lasso head...,"211,852",NaN,"[Jason Sudeikis, Brett Goldstein, Brendan Hunt...",NaN,"Comedy, Drama, Sport",30 min
8,Extraction,6.7,"Tyler Rake, a fearless black market mercenary,...","203,467",[Sam Hargrave],"[Chris Hemsworth, Bryon Lerum, Ryder Lerum, Ru...",56,"Action, Thriller",116 min
9,Enola Holmes,6.6,When Enola Holmes-Sherlock's teen sister-disco...,"188,504",[Harry Bradbeer],"[Millie Bobby Brown, Henry Cavill, Sam Claflin...",68,"Action, Adventure, Crime",123 min

In [15]:
result = []
number_of_pages = 20 # 1000/50 = 20
for i in range(1, number_of_pages + 1):
    result.append(imdb_data(i))

In [16]:
list2 = []
def flatten(list1):
    for sublist1 in list1:
        for sublist2 in sublist1:
            list2.append(sublist2)
    return list2

In [17]:
movies_df = pd.DataFrame(flatten(result), columns = ['Movie Name', 'IMDB Rating', 'Description','Votes', 'Directors','Stars', 'Metascore', 'Genre', 'Duration'])

In [18]:
movies_df.head(10)

,Movie Name,IMDB Rating,Description,Votes,Directors,Stars,Metascore,Genre,Duration
0,Tenet,7.3,"Armed with only one word, Tenet, and fighting ...","500,805",[Christopher Nolan],"[John David Washington, Robert Pattinson, Eliz...",69,"Action, Sci-Fi, Thriller",150 min
1,The Queen's Gambit,8.6,"Orphaned at the tender age of nine, prodigious...","445,361",NaN,"[Anya Taylor-Joy, Chloe Pirrie, Bill Camp, Mar...",NaN,Drama,60 min
2,Soul,8.0,"After landing the gig of a lifetime, a New Yor...","328,330","[Pete Docter, Kemp Powers]","[Jamie Foxx, Tina Fey, Graham Norton, Rachel H...",83,"Animation, Adventure, Comedy",100 min
3,Wonder Woman 1984,5.4,"Diana must contend with a work colleague, and ...","267,158",[Patty Jenkins],"[Gal Gadot, Chris Pine, Kristen Wiig, Pedro Pa...",60,"Action, Adventure, Fantasy",151 min
4,Birds of Prey and the Fantabulous Emancipation...,6.0,"After splitting with the Joker, Harley Quinn j...","239,262",[Cathy Yan],"[Margot Robbie, Rosie Perez, Mary Elizabeth Wi...",60,"Action, Adventure, Comedy",109 min
5,The Invisible Man,7.1,When Cecilia's abusive ex takes his own life a...,"228,816",[Leigh Whannell],"[Elisabeth Moss, Oliver Jackson-Cohen, Harriet...",72,"Drama, Horror, Mystery",124 min
6,A Quiet Place Part II,7.2,"Following the events at home, the Abbott famil...","227,288",[John Krasinski],"[Emily Blunt, Millicent Simmonds, Cillian Murphy]",71,"Drama, Horror, Sci-Fi",97 min
7,Ted Lasso,8.8,American college football coach Ted Lasso head...,"211,852",NaN,"[Jason Sudeikis, Brett Goldstein, Brendan Hunt...",NaN,"Comedy, Drama, Sport",30 min
8,Extraction,6.7,"Tyler Rake, a fearless black market mercenary,...","203,467",[Sam Hargrave],"[Chris Hemsworth, Bryon Lerum, Ryder Lerum, Ru...",56,"Action, Thriller",116 min
9,Enola Holmes,6.6,When Enola Holmes-Sherlock's teen sister-disco...,"188,504",[Harry Bradbeer],"[Millie Bobby Brown, Henry Cavill, Sam Claflin...",68,"Action, Adventure, Crime",123 min

In [19]:
movies_df.shape

(1000, 9)